### ISSUE TITLE
Pattern Scan return multiple values?

### ISSUE THREAD

**Issue by Rednick16** [ItsJustMeChris/m0ch4#1]
can you make the pattern scan return multiple values? in a std::vector it might already have that feature but i can't get it to return me those values

i did vec.push_back(FindPattern(base, pattern, size))

**Comment by ItsJustMeChris** [comment]
I have this in a local branch, I'll merge it in tomorrow morning. Sorry for the late response.

**Comment by ItsJustMeChris** [comment]
Added FindAllPattern

@ https://github.com/ItsJustMeChris/m0ch4/commit/498faccd3dec6d81769df32757717d63075c2b52
